###
POST http://localhost:3500/imovel
Content-Type: application/json

{
  "tipoImovel": "Condominio",
  "endereco": "Rua das Flores, 123",
  "latitude": "-22.91044817063489",
  "longitude" :"-43.17330303796755",
  "caracteristicas": "3 quartos, 2 banheiros",
  "preco": "R$ 500.000,00",
  "informacoesAdicionais": "Excelente localização",
  "fotos": ["https://projetaronline.com/wp-content/uploads/2024/02/Casa-de-Campo-em-L-com-3-quatos_01-Foto.webp", "https://projetaronline.com/wp-content/uploads/2024/02/Casa-de-Campo-em-L-com-3-quatos_12-Foto.webp"],
  "usuarioId": 1,
  "status": 1
}

### buscar por id
GET http://localhost:3500/imovel/1
Content-Type: application/json

### Listar todos por id do usuário
GET http://localhost:3500/imovel/user/1
Content-Type: application/json

### Listar todos
GET http://localhost:3500/imovel
Content-Type: application/json


### Update
PATCH http://localhost:3500/imovel/1
Content-Type: application/json

{
  "tipoImovel": "condominio"
}

### 
DELETE http://localhost:3500/imovel/1
Content-Type: application/json